# Identidad del servicio
spring.application.name=servicio-donaciones

# Configuración de Base de Datos
spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.database-platform=${DB_DIALECT:org.hibernate.dialect.H2Dialect}

# Habilitar H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate y Observabilidad de DB
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.generate_statistics=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=always

# DevTools & Server Configuration
spring.devtools.restart.enabled=true
server.port=${PORT:8080}

# Datadog Metrics Configuration
management.datadog.metrics.export.enabled=${DD_METRICS_ENABLED:false}
management.datadog.metrics.export.api-key=${DD_API_KEY:}
management.datadog.metrics.export.uri=${DD_URI:https://api.datadoghq.com}
management.datadog.metrics.export.step=30s

# URLs de integracion con otros modulos
url.donadores=${URL_DONADORES:https://agusb1101-donadores-entidades.onrender.com}
url.logistica=${URL_LOGISTICA:https://logistica-hjaw.onrender.com}